TITLE="Hướng dẫn Lập trình Mạng của Beej"
SUBTITLE="Dùng Socket Internet"
AUTHOR='Brian “Beej Jorgensen” Hall (bản dịch tiếng Việt của Duc-Tam Nguyen)'
VERSION_DATE="v3.3.2, Copyright © April 18, 2026"

GUIDE_ID=bgnet
BGBSPD_BUILD_DIR?=../../bgbspd

WEB_IMAGES=$(wildcard *.svg)
EPUB_SVGS=$(wildcard *.svg)

include $(BGBSPD_BUILD_DIR)/source.make
